<a href="https://colab.research.google.com/github/gurram-rohith/MDS-LAB/blob/main/Pandas%20and%20Dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
s=pd.Series([73,20,17,18,19])
s

0    73
1    20
2    17
3    18
4    19
dtype: int64

In [7]:
s2=pd.Series([73,20,17,18,19],index=["a","b","c","d","e"])
s2

a    73
b    20
c    17
d    18
e    19
dtype: int64

In [18]:
df=pd.DataFrame({
    "Name":["Kohli","Rohit","Dhoni"],
    "Age":[37,38,42],
    "Iplruns":[9130,8000,7200],
    "IPL team":["RCB","MI","CSK"]
})

In [19]:
print(df)

    Name  Age  Iplruns IPL team
0  Kohli   37     9130      RCB
1  Rohit   38     8000       MI
2  Dhoni   42     7200      CSK

In [22]:
data = [
    ["Kohli", 37, 9130, "RCB"],
    ["Rohit", 38, 8000, "MI"],
    ["Dhoni", 42, 7200, "CSK"]
]
columns = ["Name", "Age", "Iplruns", "IPL team"]
df2 = pd.DataFrame(data, columns=columns)

In [26]:
data_dict_list = [
    {"Name": "Kohli", "Age": 37, "Iplruns": 9130, "IPL team": "RCB"},
    {"Name": "Rohit", "Age": 38, "Iplruns": 8000, "IPL team": "MI"},
    {"Name": "Dhoni", "Age": 42, "Iplruns": 7200, "IPL team": "CSK"}
]
df_from_dict_list = pd.DataFrame(data_dict_list)
display(df_from_dict_list)

    Name  Age  Iplruns IPL team
0  Kohli   37     9130      RCB
1  Rohit   38     8000       MI
2  Dhoni   42     7200      CSK

In [27]:
s3 = pd.Series([10, 20, 30, 40], name="Numbers")
df_from_series = pd.DataFrame(s3)
display(df_from_series)

   Numbers
0       10
1       20
2       30
3       40

In [28]:
df_from_multiple_series = pd.DataFrame({"Series1": s, "Series2": s2.values})
display(df_from_multiple_series)

   Series1  Series2
0       73       73
1       20       20
2       17       17
3       18       18
4       19       19

### Importing a CSV File into a DataFrame
You can use `pd.read_csv()` to load data from a CSV file. Replace `'your_file.csv'` with the actual path to your CSV file.

In [47]:
try:
    df_csv = pd.read_csv('/content/sample_data/california_housing_test.csv')
    print("DataFrame loaded successfully from 'california_housing_test.csv':")
    display(df_csv)
except FileNotFoundError:
    print("Error: The specified CSV file was not found. Please provide the correct path.")
except Exception as e:
    print(f"An error occurred: {e}")

DataFrame loaded successfully from 'california_housing_test.csv':

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
...,...,...,...,...,...,...,...,...,...
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [35]:
print(df_csv.tail())

      longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
2995    -119.86     34.42                23.0       1450.0           642.0
2996    -118.14     34.06                27.0       5257.0          1082.0
2997    -119.70     36.30                10.0        956.0           201.0
2998    -117.12     34.10                40.0         96.0            14.0
2999    -119.63     34.42                42.0       1765.0           263.0

      population  households  median_income  median_house_value
2995      1258.0       607.0         1.1790            225000.0
2996      3496.0      1036.0         3.3906            237200.0
2997       693.0       220.0         2.2895             62000.0
2998        46.0        14.0         3.2708            162500.0
2999       753.0       260.0         8.5608            500001.0

In [40]:
display(df_csv.head(10))

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0
5,-119.56,36.51,37.0,1018.0,213.0,663.0,204.0,1.6635,67000.0
6,-121.43,38.63,43.0,1009.0,225.0,604.0,218.0,1.6641,67000.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [41]:
display(df_csv.tail(10))

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
2990,-118.23,34.09,49.0,1638.0,456.0,1500.0,430.0,2.6923,150000.0
2991,-117.17,34.28,13.0,4867.0,718.0,780.0,250.0,7.1997,253800.0
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0
2994,-117.93,33.86,35.0,931.0,181.0,516.0,174.0,5.5867,182500.0
2995,-119.86,34.42,23.0,1450.0,642.0,1258.0,607.0,1.1790,225000.0
2996,-118.14,34.06,27.0,5257.0,1082.0,3496.0,1036.0,3.3906,237200.0
2997,-119.70,36.30,10.0,956.0,201.0,693.0,220.0,2.2895,62000.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0

In [42]:
print(df_csv.shape)

(3000, 9)

In [44]:
display(df_csv.columns)

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [49]:
print("Index of df_csv:")
display(df_csv.index)

Index of df_csv:

RangeIndex(start=0, stop=3000, step=1)

In [50]:
print(df_csv["population"]>=1200)

0        True
1       False
2        True
3       False
4       False
        ...
2995     True
2996     True
2997    False
2998    False
2999    False
Name: population, Length: 3000, dtype: bool

In [59]:
df_filtered_population = df_csv[df_csv["population"] >= 1200]
print("Records where population >= 1200:")
display(df_filtered_population.head())

Records where population >= 1200:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
7,-120.65,35.48,19.0,2310.0,471.0,1341.0,441.0,3.2250,166900.0
8,-122.84,38.40,15.0,3080.0,617.0,1446.0,599.0,3.6696,194400.0
9,-118.02,34.08,31.0,2402.0,632.0,2830.0,603.0,2.3333,164200.0

In [66]:
df_2=df_csv['median_income'].rank(ascending=False)

0        199.0
1       1423.0
2        362.0
3        278.0
4       1944.0
         ...
2995    2945.0
2996    1567.0
2997    2441.0
2998    1654.5
2999      64.0
Name: median_income, Length: 3000, dtype: float64

In [65]:
df_2.head()

0     199.0
1    1423.0
2     362.0
3     278.0
4    1944.0
Name: median_income, dtype: float64

In [67]:
print('Ranks sorted in descending order (highest median_income first):')
display(df_2.sort_values(ascending=True).head())

Ranks sorted in descending order (highest median_income first):

42      5.0
1600    5.0
2199    5.0
1475    5.0
161     5.0
Name: median_income, dtype: float64

In [72]:
print('Full ranks for median_income:')
display(df_2)

Full ranks for median_income:

0        199.0
1       1423.0
2        362.0
3        278.0
4       1944.0
         ...
2995    2945.0
2996    1567.0
2997    2441.0
2998    1654.5
2999      64.0
Name: median_income, Length: 3000, dtype: float64

In [73]:
df_csv['median_income_rank'] = df_2
print('df_csv with new median_income_rank column:')
display(df_csv.head())

df_csv with new median_income_rank column:

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,median_income_rank
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,199.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,1423.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,362.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,278.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,1944.0

In [74]:
df_11=df_csv.sort_values("median_house_value")
display(df_11)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,median_income_rank
2001,-117.16,32.71,52.0,845.0,451.0,1230.0,375.0,1.0918,22500.0,2961.0
1031,-123.08,40.40,10.0,365.0,102.0,140.0,49.0,1.7969,37500.0,2741.0
2740,-119.97,36.44,18.0,1128.0,237.0,772.0,220.0,2.1771,39200.0,2525.0
734,-117.65,35.00,36.0,1184.0,316.0,672.0,241.0,1.9107,39800.0,2673.5
2555,-122.06,37.39,22.0,1236.0,290.0,413.0,274.0,3.6875,40000.0,1346.5
...,...,...,...,...,...,...,...,...,...,...
2999,-119.63,34.42,42.0,1765.0,263.0,753.0,260.0,8.5608,500001.0,64.0
2152,-118.43,33.96,20.0,1901.0,270.0,704.0,254.0,8.7819,500001.0,60.0
2992,-122.33,37.39,52.0,573.0,102.0,232.0,92.0,6.2263,500001.0,254.0
2968,-119.23,34.17,18.0,6171.0,1490.0,2164.0,1210.0,3.6875,500001.0,1346.5
2993,-117.91,33.60,37.0,2088.0,510.0,673.0,390.0,5.1048,500001.0,557.0

In [75]:
print(df_11.describe())

         longitude    latitude  housing_median_age   total_rooms  \
count  3000.000000  3000.00000         3000.000000   3000.000000
mean   -119.589200    35.63539           28.845333   2599.578667
std       1.994936     2.12967           12.555396   2155.593332
min    -124.180000    32.56000            1.000000      6.000000
25%    -121.810000    33.93000           18.000000   1401.000000
50%    -118.485000    34.27000           29.000000   2106.000000
75%    -118.020000    37.69000           37.000000   3129.000000
max    -114.490000    41.92000           52.000000  30450.000000

       total_bedrooms    population  households  median_income  \
count     3000.000000   3000.000000  3000.00000    3000.000000
mean       529.950667   1402.798667   489.91200       3.807272
std        415.654368   1030.543012   365.42271       1.854512
min          2.000000      5.000000     2.00000       0.499900
25%        291.000000    780.000000   273.00000       2.544000
50%        437.000000   1155.000000   409.50000       3.487150
75%        636.000000   1742.750000   597.25000       4.656475
max       5419.000000  11935.000000  4930.00000      15.000100

       median_house_value  median_income_rank
count          3000.00000         3000.000000
mean         205846.27500         1500.500000
std          113119.68747          866.169596
min           22500.00000            5.000000
25%          121200.00000          750.750000
50%          177650.00000         1500.500000
75%          263975.00000         2250.375000
max          500001.00000         3000.000000

In [82]:
print(df_11["median_income"].unique())

[1.0918 1.7969 2.1771 ... 8.7819 6.2263 5.1048]

In [87]:
print("Original columns:")
display(df_csv.columns)


df_renamed_single = df_csv.rename(columns={'median_income': 'MedianIncome'})
print("\nDataFrame after renaming 'median_income' to 'MedianIncome':")
display(df_renamed_single.head())


df_renamed_multiple = df_csv.rename(columns={
    'housing_median_age': 'HousingAge',
    'total_rooms': 'TotalRooms',
    'total_bedrooms': 'TotalBedrooms'
})
print("\nDataFrame after renaming multiple columns:")
display(df_renamed_multiple.head())

Original columns:

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value', 'median_income_rank'],
      dtype='object')

DataFrame after renaming 'median_income' to 'MedianIncome':

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,MedianIncome,median_house_value,median_income_rank
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,199.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,1423.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,362.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,278.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,1944.0

DataFrame after renaming multiple columns:

,longitude,latitude,HousingAge,TotalRooms,TotalBedrooms,population,households,median_income,median_house_value,median_income_rank
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0,199.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0,1423.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0,362.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0,278.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0,1944.0